[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "midnight-magnolia-website"
source = "midnight-magnolia/midnight-magnolia" 